//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  tutorial: Tutorial;
  tutorialConnection: TutorialConnection;
  doc: Doc;
  docConnection: DocConnection;
  news: News;
  newsConnection: NewsConnection;
  practiceLab: PracticeLab;
  practiceLabConnection: PracticeLabConnection;
  showcase: Showcase;
  showcaseConnection: ShowcaseConnection;
  tool: Tool;
  toolConnection: ToolConnection;
  request: Request;
  requestConnection: RequestConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTutorialArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTutorialConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TutorialFilter>;
};


export type QueryDocArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocFilter>;
};


export type QueryNewsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNewsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsFilter>;
};


export type QueryPracticeLabArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPracticeLabConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PracticeLabFilter>;
};


export type QueryShowcaseArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryShowcaseConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ShowcaseFilter>;
};


export type QueryToolArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryToolConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ToolFilter>;
};


export type QueryRequestArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryRequestConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RequestFilter>;
};

export type DocumentFilter = {
  tutorial?: InputMaybe<TutorialFilter>;
  doc?: InputMaybe<DocFilter>;
  news?: InputMaybe<NewsFilter>;
  practiceLab?: InputMaybe<PracticeLabFilter>;
  showcase?: InputMaybe<ShowcaseFilter>;
  tool?: InputMaybe<ToolFilter>;
  request?: InputMaybe<RequestFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Tutorial | Doc | News | PracticeLab | Showcase | Tool | Request | Folder;

export type Tutorial = Node & Document & {
  __typename?: 'Tutorial';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  description: Scalars['String']['output'];
  category: Scalars['String']['output'];
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  techStack?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  difficulty?: Maybe<Scalars['String']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  videoUrl?: Maybe<Scalars['String']['output']>;
  thumbnail?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  date: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type TutorialFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  techStack?: InputMaybe<StringFilter>;
  difficulty?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  videoUrl?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  featured?: InputMaybe<BooleanFilter>;
  date?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type TutorialConnectionEdges = {
  __typename?: 'TutorialConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tutorial>;
};

export type TutorialConnection = Connection & {
  __typename?: 'TutorialConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TutorialConnectionEdges>>>;
};

export type Doc = Node & Document & {
  __typename?: 'Doc';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  category: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  lastUpdated?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type DocFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  lastUpdated?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type DocConnectionEdges = {
  __typename?: 'DocConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Doc>;
};

export type DocConnection = Connection & {
  __typename?: 'DocConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocConnectionEdges>>>;
};

export type News = Node & Document & {
  __typename?: 'News';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  summary: Scalars['String']['output'];
  source: Scalars['String']['output'];
  sourceUrl?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  imageUrl?: Maybe<Scalars['String']['output']>;
  publishedAt: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  readTime?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NewsFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  source?: InputMaybe<StringFilter>;
  sourceUrl?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  imageUrl?: InputMaybe<ImageFilter>;
  publishedAt?: InputMaybe<DatetimeFilter>;
  category?: InputMaybe<StringFilter>;
  readTime?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type NewsConnectionEdges = {
  __typename?: 'NewsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<News>;
};

export type NewsConnection = Connection & {
  __typename?: 'NewsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NewsConnectionEdges>>>;
};

export type PracticeLab = Node & Document & {
  __typename?: 'PracticeLab';
  title: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  description: Scalars['String']['output'];
  environment?: Maybe<Scalars['String']['output']>;
  difficulty?: Maybe<Scalars['String']['output']>;
  status?: Maybe<Scalars['String']['output']>;
  usersOnline?: Maybe<Scalars['Float']['output']>;
  thumbnail?: Maybe<Scalars['String']['output']>;
  launchUrl?: Maybe<Scalars['String']['output']>;
  launchMode?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PracticeLabFilter = {
  title?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  environment?: InputMaybe<StringFilter>;
  difficulty?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  usersOnline?: InputMaybe<NumberFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  launchUrl?: InputMaybe<StringFilter>;
  launchMode?: InputMaybe<StringFilter>;
};

export type PracticeLabConnectionEdges = {
  __typename?: 'PracticeLabConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PracticeLab>;
};

export type PracticeLabConnection = Connection & {
  __typename?: 'PracticeLabConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PracticeLabConnectionEdges>>>;
};

export type ShowcaseAuthor = {
  __typename?: 'ShowcaseAuthor';
  name: Scalars['String']['output'];
  avatar?: Maybe<Scalars['String']['output']>;
};

export type Showcase = Node & Document & {
  __typename?: 'Showcase';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  contentType: Scalars['String']['output'];
  author?: Maybe<ShowcaseAuthor>;
  description: Scalars['String']['output'];
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  stars?: Maybe<Scalars['Float']['output']>;
  demoUrl?: Maybe<Scalars['String']['output']>;
  videoUrl?: Maybe<Scalars['String']['output']>;
  repoUrl?: Maybe<Scalars['String']['output']>;
  websiteUrl?: Maybe<Scalars['String']['output']>;
  thumbnail?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ShowcaseAuthorFilter = {
  name?: InputMaybe<StringFilter>;
  avatar?: InputMaybe<ImageFilter>;
};

export type ShowcaseFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  contentType?: InputMaybe<StringFilter>;
  author?: InputMaybe<ShowcaseAuthorFilter>;
  description?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  stars?: InputMaybe<NumberFilter>;
  demoUrl?: InputMaybe<StringFilter>;
  videoUrl?: InputMaybe<StringFilter>;
  repoUrl?: InputMaybe<StringFilter>;
  websiteUrl?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ShowcaseConnectionEdges = {
  __typename?: 'ShowcaseConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Showcase>;
};

export type ShowcaseConnection = Connection & {
  __typename?: 'ShowcaseConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ShowcaseConnectionEdges>>>;
};

export type Tool = Node & Document & {
  __typename?: 'Tool';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  description: Scalars['String']['output'];
  category: Scalars['String']['output'];
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  logoUrl?: Maybe<Scalars['String']['output']>;
  websiteUrl?: Maybe<Scalars['String']['output']>;
  repoUrl?: Maybe<Scalars['String']['output']>;
  docsUrl?: Maybe<Scalars['String']['output']>;
  pricing?: Maybe<Scalars['String']['output']>;
  stars?: Maybe<Scalars['Float']['output']>;
  license?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  date: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ToolFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  logoUrl?: InputMaybe<ImageFilter>;
  websiteUrl?: InputMaybe<StringFilter>;
  repoUrl?: InputMaybe<StringFilter>;
  docsUrl?: InputMaybe<StringFilter>;
  pricing?: InputMaybe<StringFilter>;
  stars?: InputMaybe<NumberFilter>;
  license?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  date?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ToolConnectionEdges = {
  __typename?: 'ToolConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tool>;
};

export type ToolConnection = Connection & {
  __typename?: 'ToolConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ToolConnectionEdges>>>;
};

export type Request = Node & Document & {
  __typename?: 'Request';
  topic: Scalars['String']['output'];
  category: Scalars['String']['output'];
  description: Scalars['String']['output'];
  email?: Maybe<Scalars['String']['output']>;
  status?: Maybe<Scalars['String']['output']>;
  submittedAt?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RequestFilter = {
  topic?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  submittedAt?: InputMaybe<DatetimeFilter>;
};

export type RequestConnectionEdges = {
  __typename?: 'RequestConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Request>;
};

export type RequestConnection = Connection & {
  __typename?: 'RequestConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<RequestConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateTutorial: Tutorial;
  createTutorial: Tutorial;
  updateDoc: Doc;
  createDoc: Doc;
  updateNews: News;
  createNews: News;
  updatePracticeLab: PracticeLab;
  createPracticeLab: PracticeLab;
  updateShowcase: Showcase;
  createShowcase: Showcase;
  updateTool: Tool;
  createTool: Tool;
  updateRequest: Request;
  createRequest: Request;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateTutorialArgs = {
  relativePath: Scalars['String']['input'];
  params: TutorialMutation;
};


export type MutationCreateTutorialArgs = {
  relativePath: Scalars['String']['input'];
  params: TutorialMutation;
};


export type MutationUpdateDocArgs = {
  relativePath: Scalars['String']['input'];
  params: DocMutation;
};


export type MutationCreateDocArgs = {
  relativePath: Scalars['String']['input'];
  params: DocMutation;
};


export type MutationUpdateNewsArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsMutation;
};


export type MutationCreateNewsArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsMutation;
};


export type MutationUpdatePracticeLabArgs = {
  relativePath: Scalars['String']['input'];
  params: PracticeLabMutation;
};


export type MutationCreatePracticeLabArgs = {
  relativePath: Scalars['String']['input'];
  params: PracticeLabMutation;
};


export type MutationUpdateShowcaseArgs = {
  relativePath: Scalars['String']['input'];
  params: ShowcaseMutation;
};


export type MutationCreateShowcaseArgs = {
  relativePath: Scalars['String']['input'];
  params: ShowcaseMutation;
};


export type MutationUpdateToolArgs = {
  relativePath: Scalars['String']['input'];
  params: ToolMutation;
};


export type MutationCreateToolArgs = {
  relativePath: Scalars['String']['input'];
  params: ToolMutation;
};


export type MutationUpdateRequestArgs = {
  relativePath: Scalars['String']['input'];
  params: RequestMutation;
};


export type MutationCreateRequestArgs = {
  relativePath: Scalars['String']['input'];
  params: RequestMutation;
};

export type DocumentUpdateMutation = {
  tutorial?: InputMaybe<TutorialMutation>;
  doc?: InputMaybe<DocMutation>;
  news?: InputMaybe<NewsMutation>;
  practiceLab?: InputMaybe<PracticeLabMutation>;
  showcase?: InputMaybe<ShowcaseMutation>;
  tool?: InputMaybe<ToolMutation>;
  request?: InputMaybe<RequestMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  tutorial?: InputMaybe<TutorialMutation>;
  doc?: InputMaybe<DocMutation>;
  news?: InputMaybe<NewsMutation>;
  practiceLab?: InputMaybe<PracticeLabMutation>;
  showcase?: InputMaybe<ShowcaseMutation>;
  tool?: InputMaybe<ToolMutation>;
  request?: InputMaybe<RequestMutation>;
};

export type TutorialMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  techStack?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  difficulty?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type DocMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  lastUpdated?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type NewsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  source?: InputMaybe<Scalars['String']['input']>;
  sourceUrl?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  imageUrl?: InputMaybe<Scalars['String']['input']>;
  publishedAt?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  readTime?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PracticeLabMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  environment?: InputMaybe<Scalars['String']['input']>;
  difficulty?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  usersOnline?: InputMaybe<Scalars['Float']['input']>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  launchUrl?: InputMaybe<Scalars['String']['input']>;
  launchMode?: InputMaybe<Scalars['String']['input']>;
};

export type ShowcaseAuthorMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  avatar?: InputMaybe<Scalars['String']['input']>;
};

export type ShowcaseMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  contentType?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<ShowcaseAuthorMutation>;
  description?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  stars?: InputMaybe<Scalars['Float']['input']>;
  demoUrl?: InputMaybe<Scalars['String']['input']>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
  repoUrl?: InputMaybe<Scalars['String']['input']>;
  websiteUrl?: InputMaybe<Scalars['String']['input']>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ToolMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  logoUrl?: InputMaybe<Scalars['String']['input']>;
  websiteUrl?: InputMaybe<Scalars['String']['input']>;
  repoUrl?: InputMaybe<Scalars['String']['input']>;
  docsUrl?: InputMaybe<Scalars['String']['input']>;
  pricing?: InputMaybe<Scalars['String']['input']>;
  stars?: InputMaybe<Scalars['Float']['input']>;
  license?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type RequestMutation = {
  topic?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  submittedAt?: InputMaybe<Scalars['String']['input']>;
};

export type TutorialPartsFragment = { __typename: 'Tutorial', title: string, slug: string, locale: string, description: string, category: string, tags?: Array<string | null> | null, techStack?: Array<string | null> | null, difficulty?: string | null, duration?: string | null, videoUrl?: string | null, thumbnail?: string | null, featured?: boolean | null, date: string, body?: any | null };

export type DocPartsFragment = { __typename: 'Doc', title: string, slug: string, locale: string, category: string, order?: number | null, lastUpdated?: string | null, body?: any | null };

export type NewsPartsFragment = { __typename: 'News', title: string, slug: string, locale: string, summary: string, source: string, sourceUrl?: string | null, author?: string | null, imageUrl?: string | null, publishedAt: string, category?: string | null, readTime?: string | null, body?: any | null };

export type PracticeLabPartsFragment = { __typename: 'PracticeLab', title: string, locale: string, description: string, environment?: string | null, difficulty?: string | null, status?: string | null, usersOnline?: number | null, thumbnail?: string | null, launchUrl?: string | null, launchMode?: string | null };

export type ShowcasePartsFragment = { __typename: 'Showcase', title: string, slug: string, locale: string, contentType: string, description: string, tags?: Array<string | null> | null, stars?: number | null, demoUrl?: string | null, videoUrl?: string | null, repoUrl?: string | null, websiteUrl?: string | null, thumbnail?: string | null, body?: any | null, author?: { __typename: 'ShowcaseAuthor', name: string, avatar?: string | null } | null };

export type ToolPartsFragment = { __typename: 'Tool', title: string, slug: string, locale: string, description: string, category: string, tags?: Array<string | null> | null, logoUrl?: string | null, websiteUrl?: string | null, repoUrl?: string | null, docsUrl?: string | null, pricing?: string | null, stars?: number | null, license?: string | null, featured?: boolean | null, date: string, body?: any | null };

export type RequestPartsFragment = { __typename: 'Request', topic: string, category: string, description: string, email?: string | null, status?: string | null, submittedAt?: string | null };

export type TutorialQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TutorialQuery = { __typename?: 'Query', tutorial: { __typename: 'Tutorial', id: string, title: string, slug: string, locale: string, description: string, category: string, tags?: Array<string | null> | null, techStack?: Array<string | null> | null, difficulty?: string | null, duration?: string | null, videoUrl?: string | null, thumbnail?: string | null, featured?: boolean | null, date: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TutorialConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TutorialFilter>;
}>;


export type TutorialConnectionQuery = { __typename?: 'Query', tutorialConnection: { __typename?: 'TutorialConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TutorialConnectionEdges', cursor: string, node?: { __typename: 'Tutorial', id: string, title: string, slug: string, locale: string, description: string, category: string, tags?: Array<string | null> | null, techStack?: Array<string | null> | null, difficulty?: string | null, duration?: string | null, videoUrl?: string | null, thumbnail?: string | null, featured?: boolean | null, date: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type DocQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DocQuery = { __typename?: 'Query', doc: { __typename: 'Doc', id: string, title: string, slug: string, locale: string, category: string, order?: number | null, lastUpdated?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DocConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocFilter>;
}>;


export type DocConnectionQuery = { __typename?: 'Query', docConnection: { __typename?: 'DocConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DocConnectionEdges', cursor: string, node?: { __typename: 'Doc', id: string, title: string, slug: string, locale: string, category: string, order?: number | null, lastUpdated?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type NewsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NewsQuery = { __typename?: 'Query', news: { __typename: 'News', id: string, title: string, slug: string, locale: string, summary: string, source: string, sourceUrl?: string | null, author?: string | null, imageUrl?: string | null, publishedAt: string, category?: string | null, readTime?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type NewsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsFilter>;
}>;


export type NewsConnectionQuery = { __typename?: 'Query', newsConnection: { __typename?: 'NewsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NewsConnectionEdges', cursor: string, node?: { __typename: 'News', id: string, title: string, slug: string, locale: string, summary: string, source: string, sourceUrl?: string | null, author?: string | null, imageUrl?: string | null, publishedAt: string, category?: string | null, readTime?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PracticeLabQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PracticeLabQuery = { __typename?: 'Query', practiceLab: { __typename: 'PracticeLab', id: string, title: string, locale: string, description: string, environment?: string | null, difficulty?: string | null, status?: string | null, usersOnline?: number | null, thumbnail?: string | null, launchUrl?: string | null, launchMode?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PracticeLabConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PracticeLabFilter>;
}>;


export type PracticeLabConnectionQuery = { __typename?: 'Query', practiceLabConnection: { __typename?: 'PracticeLabConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PracticeLabConnectionEdges', cursor: string, node?: { __typename: 'PracticeLab', id: string, title: string, locale: string, description: string, environment?: string | null, difficulty?: string | null, status?: string | null, usersOnline?: number | null, thumbnail?: string | null, launchUrl?: string | null, launchMode?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ShowcaseQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ShowcaseQuery = { __typename?: 'Query', showcase: { __typename: 'Showcase', id: string, title: string, slug: string, locale: string, contentType: string, description: string, tags?: Array<string | null> | null, stars?: number | null, demoUrl?: string | null, videoUrl?: string | null, repoUrl?: string | null, websiteUrl?: string | null, thumbnail?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, author?: { __typename: 'ShowcaseAuthor', name: string, avatar?: string | null } | null } };

export type ShowcaseConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ShowcaseFilter>;
}>;


export type ShowcaseConnectionQuery = { __typename?: 'Query', showcaseConnection: { __typename?: 'ShowcaseConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ShowcaseConnectionEdges', cursor: string, node?: { __typename: 'Showcase', id: string, title: string, slug: string, locale: string, contentType: string, description: string, tags?: Array<string | null> | null, stars?: number | null, demoUrl?: string | null, videoUrl?: string | null, repoUrl?: string | null, websiteUrl?: string | null, thumbnail?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, author?: { __typename: 'ShowcaseAuthor', name: string, avatar?: string | null } | null } | null } | null> | null } };

export type ToolQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ToolQuery = { __typename?: 'Query', tool: { __typename: 'Tool', id: string, title: string, slug: string, locale: string, description: string, category: string, tags?: Array<string | null> | null, logoUrl?: string | null, websiteUrl?: string | null, repoUrl?: string | null, docsUrl?: string | null, pricing?: string | null, stars?: number | null, license?: string | null, featured?: boolean | null, date: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ToolConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ToolFilter>;
}>;


export type ToolConnectionQuery = { __typename?: 'Query', toolConnection: { __typename?: 'ToolConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ToolConnectionEdges', cursor: string, node?: { __typename: 'Tool', id: string, title: string, slug: string, locale: string, description: string, category: string, tags?: Array<string | null> | null, logoUrl?: string | null, websiteUrl?: string | null, repoUrl?: string | null, docsUrl?: string | null, pricing?: string | null, stars?: number | null, license?: string | null, featured?: boolean | null, date: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type RequestQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type RequestQuery = { __typename?: 'Query', request: { __typename: 'Request', id: string, topic: string, category: string, description: string, email?: string | null, status?: string | null, submittedAt?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type RequestConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RequestFilter>;
}>;


export type RequestConnectionQuery = { __typename?: 'Query', requestConnection: { __typename?: 'RequestConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'RequestConnectionEdges', cursor: string, node?: { __typename: 'Request', id: string, topic: string, category: string, description: string, email?: string | null, status?: string | null, submittedAt?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const TutorialPartsFragmentDoc = gql`
    fragment TutorialParts on Tutorial {
  __typename
  title
  slug
  locale
  description
  category
  tags
  techStack
  difficulty
  duration
  videoUrl
  thumbnail
  featured
  date
  body
}
    `;
export const DocPartsFragmentDoc = gql`
    fragment DocParts on Doc {
  __typename
  title
  slug
  locale
  category
  order
  lastUpdated
  body
}
    `;
export const NewsPartsFragmentDoc = gql`
    fragment NewsParts on News {
  __typename
  title
  slug
  locale
  summary
  source
  sourceUrl
  author
  imageUrl
  publishedAt
  category
  readTime
  body
}
    `;
export const PracticeLabPartsFragmentDoc = gql`
    fragment PracticeLabParts on PracticeLab {
  __typename
  title
  locale
  description
  environment
  difficulty
  status
  usersOnline
  thumbnail
  launchUrl
  launchMode
}
    `;
export const ShowcasePartsFragmentDoc = gql`
    fragment ShowcaseParts on Showcase {
  __typename
  title
  slug
  locale
  contentType
  author {
    __typename
    name
    avatar
  }
  description
  tags
  stars
  demoUrl
  videoUrl
  repoUrl
  websiteUrl
  thumbnail
  body
}
    `;
export const ToolPartsFragmentDoc = gql`
    fragment ToolParts on Tool {
  __typename
  title
  slug
  locale
  description
  category
  tags
  logoUrl
  websiteUrl
  repoUrl
  docsUrl
  pricing
  stars
  license
  featured
  date
  body
}
    `;
export const RequestPartsFragmentDoc = gql`
    fragment RequestParts on Request {
  __typename
  topic
  category
  description
  email
  status
  submittedAt
}
    `;
export const TutorialDocument = gql`
    query tutorial($relativePath: String!) {
  tutorial(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TutorialParts
  }
}
    ${TutorialPartsFragmentDoc}`;
export const TutorialConnectionDocument = gql`
    query tutorialConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TutorialFilter) {
  tutorialConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TutorialParts
      }
    }
  }
}
    ${TutorialPartsFragmentDoc}`;
export const DocDocument = gql`
    query doc($relativePath: String!) {
  doc(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DocParts
  }
}
    ${DocPartsFragmentDoc}`;
export const DocConnectionDocument = gql`
    query docConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DocFilter) {
  docConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DocParts
      }
    }
  }
}
    ${DocPartsFragmentDoc}`;
export const NewsDocument = gql`
    query news($relativePath: String!) {
  news(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NewsParts
  }
}
    ${NewsPartsFragmentDoc}`;
export const NewsConnectionDocument = gql`
    query newsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NewsFilter) {
  newsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NewsParts
      }
    }
  }
}
    ${NewsPartsFragmentDoc}`;
export const PracticeLabDocument = gql`
    query practiceLab($relativePath: String!) {
  practiceLab(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PracticeLabParts
  }
}
    ${PracticeLabPartsFragmentDoc}`;
export const PracticeLabConnectionDocument = gql`
    query practiceLabConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PracticeLabFilter) {
  practiceLabConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PracticeLabParts
      }
    }
  }
}
    ${PracticeLabPartsFragmentDoc}`;
export const ShowcaseDocument = gql`
    query showcase($relativePath: String!) {
  showcase(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ShowcaseParts
  }
}
    ${ShowcasePartsFragmentDoc}`;
export const ShowcaseConnectionDocument = gql`
    query showcaseConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ShowcaseFilter) {
  showcaseConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ShowcaseParts
      }
    }
  }
}
    ${ShowcasePartsFragmentDoc}`;
export const ToolDocument = gql`
    query tool($relativePath: String!) {
  tool(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ToolParts
  }
}
    ${ToolPartsFragmentDoc}`;
export const ToolConnectionDocument = gql`
    query toolConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ToolFilter) {
  toolConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ToolParts
      }
    }
  }
}
    ${ToolPartsFragmentDoc}`;
export const RequestDocument = gql`
    query request($relativePath: String!) {
  request(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...RequestParts
  }
}
    ${RequestPartsFragmentDoc}`;
export const RequestConnectionDocument = gql`
    query requestConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: RequestFilter) {
  requestConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...RequestParts
      }
    }
  }
}
    ${RequestPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      tutorial(variables: TutorialQueryVariables, options?: C): Promise<{data: TutorialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TutorialQueryVariables, query: string}> {
        return requester<{data: TutorialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TutorialQueryVariables, query: string}, TutorialQueryVariables>(TutorialDocument, variables, options);
      },
    tutorialConnection(variables?: TutorialConnectionQueryVariables, options?: C): Promise<{data: TutorialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TutorialConnectionQueryVariables, query: string}> {
        return requester<{data: TutorialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TutorialConnectionQueryVariables, query: string}, TutorialConnectionQueryVariables>(TutorialConnectionDocument, variables, options);
      },
    doc(variables: DocQueryVariables, options?: C): Promise<{data: DocQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocQueryVariables, query: string}> {
        return requester<{data: DocQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocQueryVariables, query: string}, DocQueryVariables>(DocDocument, variables, options);
      },
    docConnection(variables?: DocConnectionQueryVariables, options?: C): Promise<{data: DocConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocConnectionQueryVariables, query: string}> {
        return requester<{data: DocConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocConnectionQueryVariables, query: string}, DocConnectionQueryVariables>(DocConnectionDocument, variables, options);
      },
    news(variables: NewsQueryVariables, options?: C): Promise<{data: NewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsQueryVariables, query: string}> {
        return requester<{data: NewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsQueryVariables, query: string}, NewsQueryVariables>(NewsDocument, variables, options);
      },
    newsConnection(variables?: NewsConnectionQueryVariables, options?: C): Promise<{data: NewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsConnectionQueryVariables, query: string}> {
        return requester<{data: NewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsConnectionQueryVariables, query: string}, NewsConnectionQueryVariables>(NewsConnectionDocument, variables, options);
      },
    practiceLab(variables: PracticeLabQueryVariables, options?: C): Promise<{data: PracticeLabQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PracticeLabQueryVariables, query: string}> {
        return requester<{data: PracticeLabQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PracticeLabQueryVariables, query: string}, PracticeLabQueryVariables>(PracticeLabDocument, variables, options);
      },
    practiceLabConnection(variables?: PracticeLabConnectionQueryVariables, options?: C): Promise<{data: PracticeLabConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PracticeLabConnectionQueryVariables, query: string}> {
        return requester<{data: PracticeLabConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PracticeLabConnectionQueryVariables, query: string}, PracticeLabConnectionQueryVariables>(PracticeLabConnectionDocument, variables, options);
      },
    showcase(variables: ShowcaseQueryVariables, options?: C): Promise<{data: ShowcaseQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShowcaseQueryVariables, query: string}> {
        return requester<{data: ShowcaseQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShowcaseQueryVariables, query: string}, ShowcaseQueryVariables>(ShowcaseDocument, variables, options);
      },
    showcaseConnection(variables?: ShowcaseConnectionQueryVariables, options?: C): Promise<{data: ShowcaseConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShowcaseConnectionQueryVariables, query: string}> {
        return requester<{data: ShowcaseConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShowcaseConnectionQueryVariables, query: string}, ShowcaseConnectionQueryVariables>(ShowcaseConnectionDocument, variables, options);
      },
    tool(variables: ToolQueryVariables, options?: C): Promise<{data: ToolQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ToolQueryVariables, query: string}> {
        return requester<{data: ToolQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ToolQueryVariables, query: string}, ToolQueryVariables>(ToolDocument, variables, options);
      },
    toolConnection(variables?: ToolConnectionQueryVariables, options?: C): Promise<{data: ToolConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ToolConnectionQueryVariables, query: string}> {
        return requester<{data: ToolConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ToolConnectionQueryVariables, query: string}, ToolConnectionQueryVariables>(ToolConnectionDocument, variables, options);
      },
    request(variables: RequestQueryVariables, options?: C): Promise<{data: RequestQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RequestQueryVariables, query: string}> {
        return requester<{data: RequestQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RequestQueryVariables, query: string}, RequestQueryVariables>(RequestDocument, variables, options);
      },
    requestConnection(variables?: RequestConnectionQueryVariables, options?: C): Promise<{data: RequestConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RequestConnectionQueryVariables, query: string}> {
        return requester<{data: RequestConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RequestConnectionQueryVariables, query: string}, RequestConnectionQueryVariables>(RequestConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.1/content/1eb64df0-8ef8-46b0-badc-09899ba68ffe/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  