import { defineConfig, s } from 'velite'

export default defineConfig({
  root: 'content',
  output: {
    data: '.velite',
    assets: 'public/static',
    base: '/static/',
    clean: true,
  },
  collections: {
    tutorials: {
      name: 'Tutorial',
      pattern: 'tutorials/**/*.mdx',
      schema: s.object({
        title: s.string(),
        slug: s.string(),
        locale: s.enum(['en', 'zh', 'ja']),
        description: s.string().optional(),
        category: s.string().optional(),
        tags: s.array(s.string()).default([]),
        techStack: s.array(s.string()).default([]),
        difficulty: s.string().optional(),
        duration: s.string().optional(),
        featured: s.boolean().default(false),
        date: s.isodate(),
        thumbnail: s.string().optional(),
        videoUrl: s.string().optional(),
        body: s.raw(),
      }),
    },
    docs: {
      name: 'Doc',
      pattern: 'docs/**/*.mdx',
      schema: s.object({
        title: s.string(),
        slug: s.string(),
        locale: s.enum(['en', 'zh', 'ja']),
        category: s.string().optional(),
        order: s.number().default(0),
        lastUpdated: s.isodate().optional(),
        body: s.raw(),
      }),
    },
    news: {
      name: 'News',
      pattern: 'news/**/*.mdx',
      schema: s.object({
        title: s.string(),
        slug: s.string(),
        locale: s.enum(['en', 'zh', 'ja']),
        summary: s.string().optional(),
        source: s.string().optional(),
        sourceUrl: s.string().optional(),
        author: s.string().optional(),
        imageUrl: s.string().optional(),
        publishedAt: s.isodate(),
        category: s.string().optional(),
        readTime: s.string().optional(),
        body: s.raw(),
      }),
    },
    labs: {
      name: 'PracticeLab',
      pattern: 'labs/{en,zh,ja}/*.json',
      schema: s.object({
        title: s.string(),
        locale: s.enum(['en', 'zh', 'ja']),
        description: s.string().optional(),
        environment: s.string().optional(),
        difficulty: s.string().optional(),
        status: s.string().optional(),
        usersOnline: s.number().optional(),
        thumbnail: s.string().optional(),
        launchUrl: s.string().optional(),
        launchMode: s.string().optional(),
      }),
    },
    showcase: {
      name: 'Showcase',
      // Use only MDX files — JSON files don't have slug and are legacy
      pattern: 'showcase/**/*.mdx',
      schema: s.object({
        title: s.string(),
        slug: s.string(),
        locale: s.enum(['en', 'zh', 'ja']),
        contentType: s.string().optional(),
        author: s.object({
          name: s.string().optional(),
          avatar: s.string().optional(),
        }).optional(),
        description: s.string().optional(),
        tags: s.array(s.string()).default([]),
        stars: s.number().optional(),
        demoUrl: s.string().optional(),
        videoUrl: s.string().optional(),
        repoUrl: s.string().optional(),
        websiteUrl: s.string().optional(),
        thumbnail: s.string().optional(),
        body: s.raw(),
      }),
    },
    tools: {
      name: 'Tool',
      pattern: 'tools/**/*.mdx',
      schema: s.object({
        title: s.string(),
        slug: s.string(),
        locale: s.enum(['en', 'zh', 'ja']),
        description: s.string().optional(),
        category: s.string().optional(),
        tags: s.array(s.string()).default([]),
        logoUrl: s.string().optional(),
        websiteUrl: s.string().optional(),
        repoUrl: s.string().optional(),
        docsUrl: s.string().optional(),
        pricing: s.string().optional(),
        stars: s.number().optional(),
        license: s.string().optional(),
        featured: s.boolean().default(false),
        date: s.isodate(),
        body: s.raw(),
      }),
    },
  },
})
